const { withAppBuildGradle } = require('@expo/config-plugins');

// Points release builds at the Play Store upload keystore instead of the
// debug keystore (the RN/Expo template default, which is NOT suitable for
// a real release — see the "Caution!" comment it leaves in build.gradle).
//
// The keystore file lives at the project root (gitignored, *.jks) and the
// passwords/alias live in the user-level ~/.gradle/gradle.properties — NOT
// in this repo and NOT in android/gradle.properties, since the whole
// android/ folder gets regenerated by `expo prebuild --clean`. This plugin
// re-applies the signingConfig on every prebuild so it isn't silently lost.
module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, config => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning only supports Groovy build.gradle files');
    }
    let contents = config.modResults.contents;

    if (!contents.includes('MEALIEGO_UPLOAD_STORE_FILE')) {
      contents = contents.replace(
        /signingConfigs \{\n(\s*)debug \{/,
        `signingConfigs {\n$1release {\n$1    if (project.hasProperty('MEALIEGO_UPLOAD_STORE_FILE')) {\n$1        storeFile file(MEALIEGO_UPLOAD_STORE_FILE)\n$1        storePassword MEALIEGO_UPLOAD_STORE_PASSWORD\n$1        keyAlias MEALIEGO_UPLOAD_KEY_ALIAS\n$1        keyPassword MEALIEGO_UPLOAD_KEY_PASSWORD\n$1    }\n$1}\n$1debug {`
      );

      contents = contents.replace(
        /(release \{\s*\n\s*\/\/ Caution![^\n]*\n\s*\/\/ see[^\n]*\n\s*signingConfig signingConfigs\.)debug/,
        '$1release'
      );
    }

    config.modResults.contents = contents;
    return config;
  });
};
